### ISSUE TITLE
Uncaught TypeError: mixin is not a function

### ISSUE THREAD

**Issue by syeminpark** [croquet/worldcore#1]
Hello, the worldcore Tutorial 3 compiles with the  following error.
I haven't changed any code.
Thanks

Mixins.js:98 Uncaught TypeError: mixin is not a function
    at Mixins.js:98:1
    at Array.reduce (<anonymous>)
    at MixinFactory.with (Mixins.js:98:1)
    at ./index.js (index.js:31:33)
    at __webpack_require__ (bootstrap:161:1)
    at 0 (log.js:59:1)
    at __webpack_require__ (bootstrap:161:1)
    at bootstrap:331:1
    at bootstrap:331:1
(anonymous) @ Mixins.js:98
with @ Mixins.js:98
./index.js @ index.js:31
__webpack_require__ @ bootstrap:161
0 @ log.js:59
__webpack_require__ @ bootstrap:161
(anonymous) @ bootstrap:331
(anonymous) @ bootstrap:331

**Comment by syeminpark** [comment]
Seems to be related with the  AM_Avatar, PM_Avatar Mixins

**Comment by hidaris** [comment]
This problem still exists. I encountered it today. How did you solve it?

**Comment by bbupton** [comment]
This error is caused by trying extend an Actor or a Pawn with an improperly defined mixin. For example:

`class BadActor extends mix(Actor).with(AM_Spatial, null)`

In the future we'll work to provide better error reporting when this happens so it's easier to track down the cause. But right now, make sure the mixin list doesn't have an error.

I just checked tutorial 3, and while it might have had the issue last October, it doesn't have it now.

**Comment by hidaris** [comment]
![屏幕截图 2023-05-17 093147](https://github.com/croquet/worldcore/assets/8336146/2ef59a2d-1f03-4cc8-91ae-e55bb8fd907c)
Hi, @bbupton. I also encountered this issue in [guardians4](https://github.com/croquet/worldcore/tree/main/examples/guardians4)

**Comment by codefrau** [comment]
Please use `npx lerna bootstrap` instead of `npm install` if you are working inside the worldcore repository.

**Comment by hidaris** [comment]
> Please use `npx lerna bootstrap` instead of `npm install` if you are working inside the worldcore repository.

Thanks, I was misled by the command here before https://github.com/croquet/worldcore#modify-and-run-an-example

**Comment by codefrau** [comment]
Oh that's a good point! Brian is working on Worldcore 2.0 on the `main` branch, that's why it needs `lerna` right now.

The latest stable version was 1.4, you can switch to that by `git checkout v1.4.0`

Thank you, we should mention this in the README!

**Comment by syeminpark** [comment]
the response i got at that time was that the code was buggy and that it was better to stay away from worldcore. lol.
Glad to see worldcore getting some more love than before

**Comment by codefrau** [comment]
> the response i got at that time was that the code was buggy and that it was better to stay away from worldcore. lol.

Huh. Sounds like someone didn't take the time to properly respond back then. Telling you to stay away seems disingenious.

> Glad to see worldcore getting some more love than before

Thank you!

In any case, I just published new 2.0 pre-release packages, so for the moment `npm i` will work again.

But I also updated the README generally recommending to use `lerna` because that will work even when the published packages are not quite matching the repo anymore.
